server:
  port: 9002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: admin

security:
  oauth2:
    resource:
      id: product-catalog-rest-api
      jwt:
        key-value: secretKey