server:
  port: ${SERVICE_PORT:9002}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PASS:admin}
      database: ${MONGO_DB:admin}

security:
  oauth2:
    resource:
      id: product-catalog-rest-api
      jwt:
        key-value: secretKey

# workaround: https://stackoverflow.com/questions/46916921/spring-boot-actuator-ldap-health-endpoint-throwing-npe
management:
  health:
    ldap:
      enabled: false
  endpoint:
    health:
      show-details: always